task003/dobrye_dela/dobrye_dela/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from dobrye_dela import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^event/', include('event.urls', namespace="event")),
    url(r'^login/', 'event.views.login', name='login'),
    url(r'^logout/', 'event.views.logout', name="logout"),
    url(r'^profile/', TemplateView.as_view(template_name="event/profile.html"), name="profile"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task003/dobrye_dela/event/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.views.generic.edit import BaseCreateView
from django.views.generic.list import ListView
from event.models import Organization
from event.views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="event/index.html"), name='index'),
    url(r'^organizations$', ListView.as_view(model=Organization,
                                             template_name="event/organization_page.html",
                                             context_object_name="orgs"
                                             ), name='org'),
    url(r'^new$', add_event, name='add_event'),
    url(r'^article/new$', add_article, name='add_article'),
    url(r'^(?P<event_id>\d+)$', event_page, name='event_page'),
    url(r'^article/(?P<article_id>\d+)$', article_page, name='article_page')
    url(r'^events', show_all_ev, name='events'),
    url(r'^articles', show_all_ar, name='articles'),
    url(r'^event/(?P<post_id>\d+)', 'board.views.event',
        name='choosenEvent'),

]

task003/dobrye_dela/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Добрые дела</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li>
                <form class="navbar-form" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Поиск">
                    </div>
                    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"
                                                                        aria-hidden="true"></span>
                    </button>
                </form>
            </li>
            <li><a href="#">Мероприятия</a></li>
            <li><a href="#">Статьи</a></li>
            <li><a href="{% url 'event:org' %}">Организации</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'profile' %}">Личный кабинет</a></li>
                <li><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
                <li><a href="#">Стань участником!</a></li>
                <li><a href="{% url 'login' %}">Войти</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a href="#">О нас</a></li>
            <li><a href="#">FAQ</a></li>
            <li><a href="#">Связь с нами</a></li>
            <li><a href="#"><i class="fa fa-instagram fa-lg"></i></a></li>
            <li><a href="#"><i class="fa fa-vk fa-lg"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
        </ul>
    </div>
</nav>

<div style="min-height: 300px">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>