task003/dobrye_dela/dobrye_dela/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

from dobrye_dela import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^event/', include('event.urls', namespace="event")),
    url(r'^login/', 'event.views.login', name='login'),
    url(r'^logout/', 'event.views.logout', name="logout"),
    url(r'^profile/', TemplateView.as_view(template_name="event/profile.html"), name="profile"),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task003/dobrye_dela/event/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.views.generic.edit import BaseCreateView
from django.views.generic.list import ListView
from event.models import Organization
from event.views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="event/index.html"), name='index'),
    url(r'^organizations$', ListView.as_view(model=Organization,
                                             template_name="event/organization_page.html",
                                             context_object_name="orgs"
                                             ), name='org'),
    url(r'^new$', add_event, name='add_event'),
    url(r'^article/new$', add_article, name='add_article'),
    url(r'^(?P<event_id>\d+)$', event_page, name='event_page'),
    url(r'^article/(?P<article_id>\d+)$', article_page, name='article_page')
    url(r'^events', show_all_ev, name='events'),
    url(r'^articles', show_all_ar, name='articles'),
    url(r'^event/(?P<post_id>\d+)', 'board.views.event',
        name='choosenEvent'),

]

task003/dobrye_dela/event/models.py
# coding=utf-8
import user

import datetime
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from django.db.models.fields import DateTimeField


class UserProfile(models.Model):
    class Meta:
        db_table = 'user'
        verbose_name_plural = u'Пользователи'

    user = models.ForeignKey(User, related_name="profile")
    # name = models.CharField(max_length=50)
    # login = models.CharField(max_length=30)
    email = models.CharField(max_length=100)
    # password = models.CharField(max_length=100)
    photo = models.ImageField(null=True)
    city = models.CharField(max_length=30)
    # очки с выполненных дел
    karma = models.IntegerField(default=0)
    # done_event = models.ManyToManyField('Event', related_name="done_event", null=True)
    # done_event = models.ForeignKey('Event', related_name="done_event", null=True)
    # def __unicode__(self):
    #     return "%s: %s; %s " % (self.username, self.city, self.karma)


class Organizator(models.Model):
    class Meta:
        db_table = 'organizator'
        verbose_name_plural = u'Организаторы'

    phoneNumber = models.CharField(max_length=30)
    skypeLogin = models.CharField(max_length=30)
    # organisation = models.ForeignKey('Organization')
    event = models.ManyToManyField('Event', related_name="org_events")

    def __unicode__(self):
        return "%s: %s; " % (self.name, self.organisation)


class Organization(models.Model):
    class Meta:
        db_table = "organization"
        verbose_name_plural = u'Организации'

    name = models.CharField(max_length=100)
    likes = models.IntegerField(default=0)

    def __unicode__(self):
        return " %s ;%s " % (self.name, self.likes)


# отзыв на организацию
class Review(models.Model):
    class Meta:
        db_table = 'review'
        verbose_name_plural = u'Отзывы'

    user = models.ForeignKey(User, related_name="author_of_review")
    # организация
    organization = models.ForeignKey("Organization", null=True)
    text = models.TextField(max_length=500)
    pubDate = models.DateTimeField()

    def __unicode__(self):
        return "%s: %s; %s  " % (self.text, self.user.username, self.pubDate)


# добрые дела, события, благотворительные вечера
class Event(models.Model):
    class Meta:
        db_table = 'event'
        verbose_name_plural = u'Мероприятия'

    title = models.CharField(max_length=50)
    # category = models.ForeignKey('EventCategory')
    date = models.DateTimeField(null=True)
    photo = models.ImageField(null=True, blank=True)
    address = models.CharField(max_length=50)
    # organizator = models.ManyToManyField('Organizator', related_name="organisators")
    # organization = models.ManyToManyField('Organization', null=True)
    description = models.CharField(max_length=400)
    fileAttached = models.FileField(null=True, blank=True)
    extraLink = models.URLField(null=True, blank=True)
    # баллы к карме
    score = models.IntegerField(default=2)
    # видно всем или только зарегистрированным
    private = models.BooleanField()

    def __unicode__(self):
        return "%s: %s; %s ;%s " % (self.title, self.address, self.category.name)


# # тип мероприятия
# class CollectingEvent(Event):
#     item = models.CharField(max_length=30)
#     amount = models.IntegerField()
#
# # тип мероприятия
# class HelpingEvent(Event):
#     transport = models.ForeignKey('Transport')
#     clothType = models.ForeignKey('ClothCategory')
#     physical_difficulty = models.CharField(max_length=20)


# мотивирующие статьи
class Article(models.Model):
    class Meta:
        db_table = 'article'
        verbose_name_plural = u'Статьи'

    title = models.CharField(max_length=20, null=True)
    auther = models.ForeignKey(User, related_name="auther")
    pubTime = models.DateTimeField()
    event = models.ForeignKey('Event', null=True)
    photo = models.ImageField(null=True, blank=True)
    text = models.TextField(max_length=500)

    def __unicode__(self):
        return "%s: %s; %s ;%s " % (self.auther.name, self.event.title, self.text)


# категории мероприятий
class EventCategory(models.Model):
    class Meta:
        db_table = 'event_category'
        verbose_name_plural = u'Категории Событий'

    name = models.CharField(max_length=30)
    description = models.TextField(max_length=400)

    def __unicode__(self):
        return "%s: %s; %s ;%s " % (self.name, self.description)


class ClothCategory(models.Model):
    class Meta:
        db_table = 'cloth_category'
        verbose_name_plural = u'Категории Одежды'

    name = models.CharField(max_length=30)

    def __unicode__(self):
        return "%s " % (self.name)


class Transport(models.Model):
    class Meta:
        db_table = 'transport'
        verbose_name_plural = u'Варианты транспорта'

    type = models.CharField(max_length=30)
    cost = models.FloatField()
    capasity = models.IntegerField(default=1)

    def __unicode__(self):
        return "%s: %s; %s ;%s " % (self.type, self.capasity, self.cost)

task003/dobrye_dela/event/views.py
from datetime import datetime
from pickle import GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

# Create your views here.
from event.form import EventForm
from event.models import Event, Article


def login(request):
    if request.user.is_authenticated():
        return redirect(reverse("event:index"))
    if request.method == "GET":
        context = {}
        if "next" in request.GET:
            context["next"] = "?next=" + request.GET["next"]
        return render(request, 'event/login.html')
    elif request.method == "POST":
        user = authenticate(
            username=request.POST["username"],
            password=request.POST["password"]
        )
        if user is not None:
            auth_login(request, user)
            if "next" in request.GET:
                return redirect(request.GET["next"])
            else:
                return redirect(reverse("event:index"))
        else:
            return redirect(reverse("login"))

    else:
        return HttpResponse("405")


def logout(request):
    auth_logout(request)
    return redirect(reverse("login"))


@login_required(login_url=reverse_lazy("login"))
def add_event(request):
    if request.method == "GET":
        f = EventForm()
        return render(request, "event/add_event_page.html", {"f": f})
    elif request.method == "POST":
        f = EventForm(request.POST)
        if f.is_valid():
            ev = f.save()
            return redirect(reverse("event:event_page", args=(ev.id,)))
    else:

        return HttpResponse("405")


def event_page(request, event_id):
    if request.method == "GET":
        ev = Event.objects.get(id=event_id)
        return render(request, "event/event_page.html", {"event": ev})


def article_page(request, article_id):
    if request.method == "GET":
        ar = Article.objects.get(id=article_id)
        return render(request, "event/article_page.html", {"article": ar})


@login_required(login_url=reverse_lazy("login"))
def add_article(request):
    if request.method == "GET":
        return render(request, "event/add_article.html", {"events": Event.objects.all()})

    elif request.method == "POST":
        ar = Article()
        ar.title = request.POST["title"]
        ar.text = request.POST["text"]
        ar.pubTime = datetime.now()
        ar.auther = request.user
        ar.id = request.POST["event"]
        ar.save()
        return redirect(reverse("event:article_page", args=(ar.id,)))
    else:
        return HttpResponse("405")

task003/dobrye_dela/event/templates/event/add_article.html
{% extends "base.html" %}
{% block title %}
    <title>Profile</title>
{% endblock %}
{% block content %}
    <form method="post" role="form">
        {% csrf_token %}
        <legend>Добавить статью</legend>

        <div class="form-group">
            <label for="title">Заголовок</label>
            <input type="text" class="form-control" name="title" id="title" placeholder="Input...title">
        </div>
        <label for="event">Мероприятие</label>
        <select name="event" id="event" class="form-control">
            {% for event in events %}
                <option value="{{ event.id }}">{{ event.title }}</option>
            {% endfor %}
        </select>

        <div class="form-group">
            <label for="text">Текст</label>
            <textarea class="form-control" name="text" id="text"></textarea>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

task003/dobrye_dela/event/templates/event/add_event_page.html
{% extends "base.html" %}
{% block title %}
    <title>Create event</title>
{% endblock %}
{% block content %}
    <form  method="post">{% csrf_token %}
        {{ f.as_p }}

        <p><input type="submit" value="save"></p>
    </form>
{% endblock %}

task003/dobrye_dela/event/templates/event/article_page.html
{% extends "base.html" %}
{% block title %}
    <title>Article page</title>
{% endblock %}
{% block content %}
    <p>{{ article.title }}</p>
    <p>{{ article.auther.username }}</p>
    <p>{{ article.pubTime }}</p>
    <p>{{ article.text }}</p>
{% endblock %}

task003/dobrye_dela/event/templates/event/event_page.html
{% extends "base.html" %}
{% block title %}
    <title>Event page</title>
{% endblock %}
{% block content %}
    <p>{{ event.title }}</p>
    <p>{{ event.address }}</p>
    <p>{% if  event.private  %}
        Закрытый
    {% else %}
        Окрытый
    {% endif %}
    </p>
{% endblock %}

task003/dobrye_dela/event/templates/event/index.html
{% extends "base.html" %}
{% block title %}
    <title>Home</title>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="page-header">
            <h1>Отдыхай, помогая</br><small>СТАНЬ ВОЛОНТЕРОМ, ГДЕ ТЫ ДЕЙСТВИТЕЛЬНО НУЖЕН</small></h1>
        </div>

    </div>
{#    <h1>Отдыхай, помогая</h1>#}
{#    <h3>СТАНЬ ВОЛОНТЕРОМ, ГДЕ ТЫ ДЕЙСТВИТЕЛЬНО НУЖЕН</h3>#}
{#    <h5>главное начать</h5>#}
{% endblock %}

task003/dobrye_dela/event/templates/event/login.html
{% extends "base.html" %}
{% block content %}
{#        <form action="{% url "login" %}{{ next }}" method="post" role="form">#}
{#        {% csrf_token %}#}
{#        <p><input type="text" name="username"/> </p>#}
{#        <p><input type="password" name="password"/> </p>#}
{#        <p><input type="submit" value="Войти"/> </p>#}
{#        </form>#}
    <div class="container-fluid">

        <form action="{% url "login" %}{{ next }}" method="post" role="form" >
            {% csrf_token %}
            <legend>Вход</legend>
            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">

                <div class="form-group">
                    <label for="id_username">Логин</label>
                    <input type="text" class="form-control" name="username" id="id_username">
                </div>
                <div class="form-group">
                    <label for="id_password">Пароль</label>
                    <input type="password" class="form-control" name="password" id="id_password">
                </div>
                <button type="submit" class="btn btn-primary">Войти</button>
            </div>


        </form>
    </div>

{% endblock %}

task003/dobrye_dela/event/templates/event/organization_page.html
{% extends "base.html" %}
{% block title %}
    <title>Organizations</title>
{% endblock %}
{% block content %}
    {% for org in orgs %}
        <li>{{ org }}</li>
    {% endfor %}
{% endblock %}

task003/dobrye_dela/event/templates/event/profile.html
{% extends "base.html" %}
{% block title %}
    <title>Profile</title>
{% endblock %}
{% block content %}
    <div class="page-header">
        <h1>Привет {{ user.username }}!</br>
            <small>Рады снова тебя видеть</small>
        </h1>
    </div>
    <p><a href="{% url 'event:add_event' %}">Создай мероприятие</a></p>
    <p><a href="{% url 'event:add_article' %}">Напиши статью</a></p>

{% endblock %}